[package]
name = "Burn_model"
version = "0.1.0"
edition = "2021"



[dependencies]
burn = { version = "~0.19", features = ["std", "tui", "train", "vision", "ndarray", "autodiff"], default-features = false }
burn-ndarray = "0.19.1"
burn-wgpu = "0.19.1"
burn-tensor = "0.19.1"
burn-train = "0.19.1"


image = "0.25.9"
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
anyhow = "1.0"
thiserror = "2.0.17"
tokio = { version = "1.0", features = ["full"] }
lazy_static = "1.4.0"
rayon = "1.10.0"


futures-util = "0.3"
uuid = { version = "1.0", features = ["v4"] }

env_logger = "0.11"
log = "0.4"

#dependencies  api 
actix-web = "4.4"
actix-files = "0.6"
actix-multipart = "0.7.2"


[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3